### ISSUE TITLE
User mit Rolle im Kurs?

### ISSUE THREAD

**Issue by relecand** [sudile/moodle-enrol_extern#10]
Wenn ein User vom Admin zur externen Einschreibung bestätigt ist, dann kommt es zumindest in Moodle 2.6 vor, dass dieser User zwar in einen Kurs eingeschrieben ist, aber dort keine Rolle hat.

**Comment by jojoob** [comment]
In Moodle 2.6.10 konnte ich das Problem nicht nachvollziehen.
